// <auto-generated />
using System;
using GadgetTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GadgetTracker.Migrations
{
    [DbContext(typeof(GadgetContext))]
    partial class GadgetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GadgetTracker.Models.Gadget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GadgetLocationId");

                    b.Property<string>("Name");

                    b.Property<int?>("RoommateId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("GadgetLocationId");

                    b.HasIndex("RoommateId");

                    b.ToTable("Gadgets");
                });

            modelBuilder.Entity("GadgetTracker.Models.GadgetLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("GadgetLocations");
                });

            modelBuilder.Entity("GadgetTracker.Models.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("GadgetTracker.Models.Roommate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HouseholdId");

                    b.Property<int>("age");

                    b.Property<string>("f_name");

                    b.Property<string>("l_name");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Roommates");
                });

            modelBuilder.Entity("GadgetTracker.Models.Gadget", b =>
                {
                    b.HasOne("GadgetTracker.Models.GadgetLocation", "GadgetLocation")
                        .WithMany("Gadgets")
                        .HasForeignKey("GadgetLocationId");

                    b.HasOne("GadgetTracker.Models.Roommate", "Roommate")
                        .WithMany("Gadgets")
                        .HasForeignKey("RoommateId");
                });

            modelBuilder.Entity("GadgetTracker.Models.Roommate", b =>
                {
                    b.HasOne("GadgetTracker.Models.Household", "Household")
                        .WithMany("Roommates")
                        .HasForeignKey("HouseholdId");
                });
#pragma warning restore 612, 618
        }
    }
}
